name: flutter_tuner
description: "A simple instrument tuner app built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  record: ^6.0.0
  pitch_detector_dart: ^0.0.7
  fftea: ^1.5.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dart_melty_soundfont: ^2.0.0
  flutter_pcm_sound: ^3.3.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true